name: Build and Deploy EventEase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    
    - name: Restore dependencies
      run: dotnet restore ./wwwroot/EventEase.csproj
      working-directory: ./
    
    - name: Build
      run: dotnet build ./wwwroot/EventEase.csproj --configuration Release --no-restore
      working-directory: ./
    
    - name: Publish
      run: dotnet publish ./wwwroot/EventEase.csproj -c Release -o ./publish_output
      working-directory: ./
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: eventease-app
        path: ./publish_output
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EventEase-Kaitlyn'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish_output
