name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Verify structure
      run: |
        ls -R
        echo "Project file path:"
        ls EventEase/EventEase/*.csproj

    - name: Restore
      run: dotnet restore EventEase/EventEase/EventEase.csproj
      
    - name: Build
      run: dotnet build EventEase/EventEase/EventEase.csproj --configuration Release
      
    - name: Publish
      run: dotnet publish EventEase/EventEase/EventEase.csproj -c Release -o ./publish_output
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: eventease-app
        path: ./publish_output
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EventEase-Kaitlyn'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish_output
